# permissions for end users to edit foci.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: focusio-operator
    app.kubernetes.io/managed-by: kustomize
  name: focus-editor-role
rules:
- apiGroups:
  - io.focus.core
  resources:
  - foci
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - io.focus.core
  resources:
  - foci/status
  verbs:
  - get
