---
- name: "Create ArgoCD Namespace"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ argocd_namespace | default('argocd') }}"

- name: "Install ArgoCD"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'files/argocd.yaml') }}"
    namespace: "{{ argocd_namespace | default('argocd') }}"

- name: Expose ArgoCD Server via LoadBalancer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
        namespace: "{{ argocd_namespace | default('argocd') }}"
      spec:
        selector:
          app.kubernetes.io/name: argocd-server
        ports:
          - port: 80
            targetPort: 8080
            protocol: TCP
            name: http
          - port: 443
            targetPort: 8080
            protocol: TCP
            name: https
        type: LoadBalancer

- name: "Add focus admin user to ConfigMap 'argocd-rbac-cm'"
  kubernetes.core.k8s:
    state: patched
    api_version: v1
    kind: ConfigMap
    name: argocd-rbac-cm
    namespace: "{{ argocd_namespace | default('argocd') }}"
    definition:
      data:
        policy.csv: "{{ argocd_rbac_cm.resources[0].data['policy.csv'] | default('') }}\ng, focus-admin, role:admin"

- name: "Add focus admin user to ConfigMap 'argocd-cm'"
  kubernetes.core.k8s:
    state: patched
    api_version: v1
    kind: ConfigMap
    name: argocd-cm
    namespace: "{{ argocd_namespace | default('argocd') }}"
    definition:
      data:
        accounts.focus-admin: apiKey, login

- name: "Patch admin password in Secret 'argocd-secret'"
  kubernetes.core.k8s:
    state: patched
    api_version: v1
    kind: Secret
    name: argocd-secret
    namespace: "{{ argocd_namespace | default('argocd') }}"
    definition:
      data:
        accounts.focus-admin.password: "JDJhJDEwJDRCb1padHM2c3RIdmdtNjdtcVQuS2U3TnlVMmZtU0VkYU9raUhyckhHT0d0cmY3VkQydk9T" # notsecret

- name: "Restart ArgoCD API server to apply changes"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-server
        namespace: "{{ argocd_namespace | default('argocd') }}"
      spec:
        replicas: 1
