---
- name: "Create ArgoCD Namespace"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ install_namespace | default('argocd') }}"

- name: "Install ArgoCD"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_version | default('stable') }}/manifests/install.yaml') }}"
