---
- name: "Create Prometheus Namespace"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ install_namespace | default('monitoring') }}"

- name: "Install Prometheus"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/{{ prometheus_version | default('v0.55.0') }}/bundle.yaml') }}"

- name: "Wait for Prometheus Operator to be Ready"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ prometheus_namespace | default('monitoring') }}"
    label_selectors:
      - app.kubernetes.io/name=prometheus
  until: item.status.phase == "Running"
  retries: 10
  delay: 30
  loop: "{{ resources.resources }}"
  when: resources.resources is defined
