---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foci.core.focus.io
spec:
  group: core.focus.io
  names:
    kind: Focus
    listKind: FocusList
    plural: foci
    singular: focus
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              argocdNamespace:
                type: string
              argocdVersion:
                type: string
    subresources:
      status: {}
