---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: focuses.core.example.com
spec:
  group: core.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                installNamespace:
                  type: string
                argocdVersion:
                  type: string
  scope: Namespaced
  names:
    plural: focuses
    singular: focus
    kind: Focus
    shortNames:
    - foc
